// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Constants {
	[GeneratedCode("generate_constants.py", "1.0.0.0")]
	[GalaxyConstant("int", "auto_libNtve_gf__BB_HPBarChange_lp_barID")]
	public sealed class auto_libNtve_gf__BB_HPBarChange_lp_barID {
	}
}
