// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Constants {
	[GeneratedCode("generate_constants.py", "1.0.0.0")]
	[GalaxyConstant("text[51]", "libNtve_gv__BB_Title")]
	public sealed class libNtve_gv__BB_Title {
	}
}
