// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Constants {
	[GeneratedCode("generate_constants.py", "1.0.0.0")]
	[GalaxyConstant("bool[33]", "libNtve_gv__StoryModeSavedSettingUI_Supply")]
	public sealed class libNtve_gv__StoryModeSavedSettingUI_Supply {
	}
}
