// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("actor", "ActorCreate", "actorscope as, string actorName, string content1Name, string content2Name, string content3Name")]
	public sealed class ActorCreate {
	}
}
