// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "AIAttackWaveAddUnits4", "int n1, int n2, int n3, int n4, string unitType")]
	public sealed class AIAttackWaveAddUnits4 {
	}
}
