// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "AICastCooldown", "unit u, order o, marker m, bool retreat, int timerIdx, fixed cooldown")]
	public sealed class AICastCooldown {
	}
}
