// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "AIDefaultEconomy", "int player, string hall, string gas, string food, string peon, int cap, bool peonMode")]
	public sealed class AIDefaultEconomy {
	}
}
