// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("unitgroup", "AIFindUnits", "int player, string unitType, point p, fixed range, int inMaxCount")]
	public sealed class AIFindUnits {
	}
}
