// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "AILimitTech", "int player, int totalMin, int totalGas, int buildingMin, int buildingGas, int upgradeMin, int upgradeGas")]
	public sealed class AILimitTech {
	}
}
