// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "AIWaveInfoScout", "waveinfo info, int player, point from, int time")]
	public sealed class AIWaveInfoScout {
	}
}
