// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "CameraShakeStart", "int player, int position, int direction, fixed amplitude, fixed frequency, fixed randomPercent, fixed duration")]
	public sealed class CameraShakeStart {
	}
}
