// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("fixed", "DialogControlGetPropertyAsFixed", "int control, int property, int player")]
	public sealed class DialogControlGetPropertyAsFixed {
	}
}
