// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "DialogControlInvokeAsString", "int control, playergroup players, string method, string param1, string param2, string param3, string param4")]
	public sealed class DialogControlInvokeAsString {
	}
}
