// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "DialogControlInvokeAsText", "int control, playergroup players, string method, text param1, text param2, text param3, text param4")]
	public sealed class DialogControlInvokeAsText {
	}
}
