// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "libNtve_gf_UnitGetPropertyKills", "unit lp_u, bool lp_current")]
	public sealed class libNtve_gf_UnitGetPropertyKills {
	}
}
