// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_SetBossBarBoss", "int lp_bossBarID, unit lp_boss, bool lp_refresh")]
	public sealed class libNtve_gf_SetBossBarBoss {
	}
}
