// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("fixed", "libNtve_gf_ArithmeticRealClamp", "fixed lp_value, fixed lp_min, fixed lp_max")]
	public sealed class libNtve_gf_ArithmeticRealClamp {
	}
}
