// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_UnitSetVariation", "unit lp_unit, string lp_model, int lp_percent, string lp_textures")]
	public sealed class libNtve_gf_UnitSetVariation {
	}
}
