// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_CreateExplosionAtPoint", "int lp_size, int lp_race, point lp_point")]
	public sealed class libNtve_gf_CreateExplosionAtPoint {
	}
}
