// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("point", "libNtve_gf_PointWithZOffset", "point lp_p, fixed lp_z")]
	public sealed class libNtve_gf_PointWithZOffset {
	}
}
