// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("unit", "libNtve_gf_ClosestUnitToPoint", "point lp_point, unitgroup lp_group")]
	public sealed class libNtve_gf_ClosestUnitToPoint {
	}
}
