// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_CreateUnitsWithDefaultFacing", "int lp_count, string lp_type, int lp_style, int lp_player, point lp_p")]
	public sealed class libNtve_gf_CreateUnitsWithDefaultFacing {
	}
}
