// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_SwooshCamera", "int lp_player, fixed lp_distance1, fixed lp_distance2, point lp_location, fixed lp_duration")]
	public sealed class libNtve_gf_SwooshCamera {
	}
}
