// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "libNtve_gf_ArithmeticIntClamp", "int lp_value, int lp_min, int lp_max")]
	public sealed class libNtve_gf_ArithmeticIntClamp {
	}
}
