// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("text", "libNtve_gf_FormatTipTitle", "text lp_title, int lp_type")]
	public sealed class libNtve_gf_FormatTipTitle {
	}
}
