// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("color", "libNtve_gf_DialogItemColor", "int lp_dialogItem, int lp_player")]
	public sealed class libNtve_gf_DialogItemColor {
	}
}
