// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_PortraitSetAnim", "int lp_Portrait, string lp_Anim, string lp_identifier, int lp_flags, fixed lp_blendTime")]
	public sealed class libNtve_gf_PortraitSetAnim {
	}
}
