// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_SendTransmissionSimple", "transmissionsource lp_Source, int lp_Target, soundlink lp_Sound, fixed lp_Duration, int lp_DurationType, bool lp_WaitUntilDone")]
	public sealed class libNtve_gf_SendTransmissionSimple {
	}
}
