// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_CreatePingFacingAngle", "playergroup lp_players, string lp_model, point lp_position, color lp_color, fixed lp_duration, fixed lp_angle")]
	public sealed class libNtve_gf_CreatePingFacingAngle {
	}
}
