// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_SetUpgradeLevelForPlayer", "int lp_p, string lp_upgrade, int lp_levels")]
	public sealed class libNtve_gf_SetUpgradeLevelForPlayer {
	}
}
