// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_MoveBossBar", "int lp_bossBarID, int lp_anchor, int lp_offsetX, int lp_offsetY")]
	public sealed class libNtve_gf_MoveBossBar {
	}
}
