// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("fixed", "libNtve_gf_DifficultyValueFixed", "fixed lp_easy, fixed lp_normal, fixed lp_advanced, fixed lp_expert")]
	public sealed class libNtve_gf_DifficultyValueFixed {
	}
}
