// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_MakeUnitLookAtUnit", "unit lp_unit, string lp_type, unit lp_lookAtTargetUnit, string lp_attachPoint")]
	public sealed class libNtve_gf_MakeUnitLookAtUnit {
	}
}
