// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_FlashScreenButton", "int lp_screenButtonID, fixed lp_flashTime, color lp_color1, color lp_color2")]
	public sealed class libNtve_gf_FlashScreenButton {
	}
}
