// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_UIErrorMessage", "playergroup lp_players, text lp_message, soundlink lp_sound")]
	public sealed class libNtve_gf_UIErrorMessage {
	}
}
