// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("string", "libNtve_gf_RefSetRefreshName", "string lp_actorRefName, string lp_refreshName")]
	public sealed class libNtve_gf_RefSetRefreshName {
	}
}
