// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "libNtve_gf_DifficultyValueInt", "int lp_easy, int lp_normal, int lp_advanced, int lp_expert")]
	public sealed class libNtve_gf_DifficultyValueInt {
	}
}
