// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("bool", "libNtve_gf_UnitMoverExists", "string lp_unitType, string lp_mover")]
	public sealed class libNtve_gf_UnitMoverExists {
	}
}
