// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("actor", "libNtve_gf_LookAtTargetFromUnitAttachPoint", "unit lp_unit, string lp_attachPoint")]
	public sealed class libNtve_gf_LookAtTargetFromUnitAttachPoint {
	}
}
