// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("actor", "libNtve_gf_LookAtTargetFromPointWithZOffset", "point lp_point, fixed lp_z")]
	public sealed class libNtve_gf_LookAtTargetFromPointWithZOffset {
	}
}
