// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_SetAllSoundChannelVolumes", "int lp_mode, playergroup lp_players, fixed lp_duration")]
	public sealed class libNtve_gf_SetAllSoundChannelVolumes {
	}
}
