// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_PlayerRemoveCooldown", "int lp_inPlayer, string lp_inCooldown")]
	public sealed class libNtve_gf_PlayerRemoveCooldown {
	}
}
