// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("unitgroup", "libNtve_gf_UnitCreateFacingPoint", "int lp_count, string lp_type, int lp_flags, int lp_player, point lp_pos, point lp_facing")]
	public sealed class libNtve_gf_UnitCreateFacingPoint {
	}
}
