// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_ChangeUnitDamage", "unit lp_unit, int lp_takeDeal, int lp_option")]
	public sealed class libNtve_gf_ChangeUnitDamage {
	}
}
