// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_ClearAnimationOnDoodadsInRegion", "region lp_target, string lp_doodadType, string lp_identifier")]
	public sealed class libNtve_gf_ClearAnimationOnDoodadsInRegion {
	}
}
