// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_DisplayScreenImage", "int lp_screenImageID, string lp_image, int lp_blendMode, int lp_width, int lp_height, int lp_anchor, int lp_offsetX, int lp_offsetY")]
	public sealed class libNtve_gf_DisplayScreenImage {
	}
}
