// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("bool", "libNtve_gt__BB_BossHPChanged_Func", "bool testConds, bool runActions")]
	public sealed class libNtve_gt__BB_BossHPChanged_Func {
	}
}
