// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("string", "libNtve_gf_MoverSetDestination2D", "fixed lp_x, fixed lp_y")]
	public sealed class libNtve_gf_MoverSetDestination2D {
	}
}
