// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("string", "libNtve_gf_ActorMsg4", "string lp_msgName, string lp_param1, string lp_param2, string lp_param3, string lp_param4")]
	public sealed class libNtve_gf_ActorMsg4 {
	}
}
