// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_DisplayBossBar", "int lp_bossBarID, string lp_portrait, text lp_title, int lp_max, playergroup lp_players")]
	public sealed class libNtve_gf_DisplayBossBar {
	}
}
