// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "libNtve_gf_SendActorMessageToGameRegionWithFilters", "region lp_region, int lp_intersectType, string lp_message, string lp_classFilters, string lp_terms")]
	public sealed class libNtve_gf_SendActorMessageToGameRegionWithFilters {
	}
}
