// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("string", "MakeMsgTextureSelectBySlot", "string slotName, int slotComponent, string textureExpression")]
	public sealed class MakeMsgTextureSelectBySlot {
	}
}
