// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("string", "MakeMsgRefSetFromRequest", "string refName, string subject, string effectName, int requestScope, int requestActor")]
	public sealed class MakeMsgRefSetFromRequest {
	}
}
