// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("string", "MakeMsgAnimBracketStart", "string animName, string propsOpening, string propsContent, string propsClosing, int animBracketStartFlags, fixed timeVariant, int timeType")]
	public sealed class MakeMsgAnimBracketStart {
	}
}
