// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "PlayerBeaconSetAutoCast", "int inPlayer, int inBeacon, bool enable")]
	public sealed class PlayerBeaconSetAutoCast {
	}
}
