// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "PlayerBeaconSetTargetUnit", "int inPlayer, int inBeacon, unit inUnit, bool alert")]
	public sealed class PlayerBeaconSetTargetUnit {
	}
}
