// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "PortraitCreate", "int offsetX, int offsetY, int anchor, int width, int height, string modelLink, string cameraLink, string animProps, bool visible, bool waitUntilLoaded")]
	public sealed class PortraitCreate {
	}
}
