// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "SoundChannelSetVolume", "playergroup players, int channel, fixed volume, fixed duration")]
	public sealed class SoundChannelSetVolume {
	}
}
