// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "TechTreeUnitHelpDefault", "int player, bool display")]
	public sealed class TechTreeUnitHelpDefault {
	}
}
