// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "TextTagCreate", "text inText, int inFontSize, point inPoint, fixed inHeightOffset, bool inShow, bool useFogofWar, playergroup inPlayers")]
	public sealed class TextTagCreate {
	}
}
