// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("int", "TransmissionSend", "playergroup players, transmissionsource source, int targetPortrait, string targetAnim, soundlink soundLink, text speaker, text subtitle, fixed duration, int durationType, bool waitUntilDone")]
	public sealed class TransmissionSend {
	}
}
