// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "TriggerSkippableBegin", "playergroup allowedToSkip, int requiredCount, trigger onSkip, bool testConds, bool waitUntilDone")]
	public sealed class TriggerSkippableBegin {
	}
}
