// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "TriggerAddEventUnitAbility", "trigger t, unitref u, abilcmd a, int stage, bool includeSharedAbils")]
	public sealed class TriggerAddEventUnitAbility {
	}
}
