// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "TriggerAddEventUnitBecomesIdle", "trigger t, unitref u, bool idle")]
	public sealed class TriggerAddEventUnitBecomesIdle {
	}
}
