// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("void", "UISetNextLoadingScreenTextPosition", "int anchor, int offsetX, int offsetY, int width, int height")]
	public sealed class UISetNextLoadingScreenTextPosition {
	}
}
