// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("bool", "UnitGroupIssueOrder", "unitgroup inGroup, order inOrder, int inQueueType")]
	public sealed class UnitGroupIssueOrder {
	}
}
