// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("fixed", "UnitGetChargeRegen", "unit inUnit, string inCharge")]
	public sealed class UnitGetChargeRegen {
	}
}
