// This code was generated by a tool.

using System;
using System.CodeDom.Compiler;

namespace Vestras.StarCraft2.Grape.Galaxy.Interop.NativeApi.Functions {
	[GeneratedCode("generate_functions.py", "1.0.0.0")]
	[GalaxyFunction("unitfilter", "UnitFilter", "int inRequired1, int inRequired2, int inExcluded1, int inExcluded2")]
	public sealed class UnitFilter {
	}
}
